In [ ]:
import pandas as pd

In [ ]:
a=pd.read_csv("/content/customer_churn_dataset.csv")

In [ ]:
a.head()

   Age  Tenure  MonthlySpend  Churn
0   45       8          1487      0
1   27       1          1124      0
2   48       4           254      0
3   45       1          1866      0
4   29       8           999      0

In [ ]:
a.tail()

     Age  Tenure  MonthlySpend  Churn
295   45       2          1004      0
296   46       6          1394      0
297   28       3          1135      0
298   45       4          1185      0
299   41       1           382      1

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           300 non-null    int64
 1   Tenure        300 non-null    int64
 2   MonthlySpend  300 non-null    int64
 3   Churn         300 non-null    int64
dtypes: int64(4)
memory usage: 9.5 KB

In [ ]:
a.describe()

              Age      Tenure  MonthlySpend       Churn
count  300.000000  300.000000    300.000000  300.000000
mean    39.530000    4.970000   1101.313333    0.070000
std     11.360427    2.586775    519.694818    0.255573
min     20.000000    1.000000    203.000000    0.000000
25%     30.000000    3.000000    678.250000    0.000000
50%     40.000000    5.000000   1133.000000    0.000000
75%     49.000000    7.000000   1516.000000    0.000000
max     59.000000    9.000000   1999.000000    1.000000

In [ ]:
a["Churn"].value_counts()

Churn
0    279
1     21
Name: count, dtype: int64

In [ ]:
x=a[["Age","Tenure","MonthlySpend"]]
y=a['Churn']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
pred=model.predict(x_test)
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,pred)

0.95

In [ ]:
confusion_matrix(y_test,pred)

array([[55,  0],
       [ 3,  2]])

In [ ]:
model.predict([[50,2,206]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
a.corr()

                   Age    Tenure  MonthlySpend     Churn
Age           1.000000  0.012948     -0.057609  0.040167
Tenure        0.012948  1.000000      0.044373 -0.381288
MonthlySpend -0.057609  0.044373      1.000000 -0.343477
Churn         0.040167 -0.381288     -0.343477  1.000000